var KBContent = {
		home: {
			bg: "bg",
			title: "We are Key + Bindings.",
			text: "Key + Bindings is a digital media agency located in London, Ontario. Here at Key + Bindings, our goal is to provide functional yet beautifully crafted web design to individuals, agencies, and businesses.",
			team1: "",
			teamImg1: "1x1",
			teamBio1: "",
			team2: "",
			teamImg2: "1x1",
			teamBio2: "",
			quote1: "",
			quote1Author:"",
			quote2: "",
			quote2Author:"",
			quote3: "",
			quote3Author:""
		},
		about: {
			bg: "about",
			title: "About Us.",
			text: "",
			team1: "Meet Liam.",
			teamImg1: "liam",
			teamBio1: "Liam is a baby-faced, go-getter who enjoys writing code and is a web developer for Key + Bindings. His passion for web development can only be rivalled by his passion for iced tea. Liam was born and raised in London, Ontario and has no intention of leaving the city ever.In his spare time Liam enjoys viewing cool websites for inspiration, supporting the ginger community, and eating McDonald’s hash browns. He does not listen to music or read books.",
			team2: "Meet Jillian.",
			teamImg2: "jill",
			teamBio2: "Jillian is a Ryan Gosling enthusiast with a strong passion for mostly Ryan Gosling related material, but also front-end web development & design. As the second half of the web development team at Key + Bindings, Jillian brings enthusiasm and creativity to the world of web development. She is overeducated in all the wrong subjects, but firmly believes that one can never be overdressed or over overeducated.",			
			quote1: "",
			quote1Author:"",
			quote2: "",
			quote2Author:"",
			quote3: "",
			quote3Author:""
		},
		testimonials: {
			bg: "clients",
			title: "Testimonials.",
			text: "",
			team1: "",
			teamImg1: "1x1",
			teamBio1: "",
			team2: "",
			teamImg2: "1x1",
			teamBio2: "",
			quote1: "I can't say enough about Key + Bindings. We've seen amazing results already.",
			quote1Author: "- Thatch D.",
			quote2: "I'd be lost without Key + Bindings. Key + Bindings is worth much more than I paid. Buy this now. I can't say enough about Key + Bindings.",
			quote2Author: "- Onida O.",
			quote3: "The service was excellent. Thank You!",
			quote3Author: "- Ibrahim U.",
		}
	};